version: v2.12.2
name: legibility-golangci-lint
destination: ./bin
plugins:
  - module: github.com/yowainwright/go-lint-legibility
    import: github.com/yowainwright/go-lint-legibility/plugin
    path: .
